In [2]:
%%latex
$A=\left[\begin{array}{cccc}1 & 3 & 7 & 2 \\ 5 & 8 & -9 & 0 \\ 6 & -7 & 11 & 12\end{array}\right]$

<IPython.core.display.Latex object>

In [3]:
%%latex
$a=\left[\begin{array}{l}1 \\ 3 \\ 7 \\ 2\end{array}\right]$

<IPython.core.display.Latex object>

In [4]:
import numpy as np
a = np.array([[1],
        [3],
        [7],
        [2]])
print("a =", a)
A = np.array([[1, 3, 7, 2],
        [5, 8, -9, 0],
        [6, -7, 11, 12]])
print("A =", A)


a = [[1]
 [3]
 [7]
 [2]]
A = [[ 1  3  7  2]
 [ 5  8 -9  0]
 [ 6 -7 11 12]]


In [5]:
%%latex
There is a Matrix feature in the NumPy Library, called as numpy.matrix, but it is no longer recommended to use this class. Regular arrays shoyld be used.

<IPython.core.display.Latex object>

In [10]:
%%latex
Given the following: $\quad A=\left[\begin{array}{cc}0 & 1 \\ -2 & -3\end{array}\right] \quad B=\left[\begin{array}{cc}1 & 0 \\ 3 & -2\end{array}\right]$



<IPython.core.display.Latex object>

In [11]:
%%latex
Matrix Addition:

$$
A+\mathrm{B}=\left[\begin{array}{cc}
0 & 1 \\
-2 & -3
\end{array}\right]+\left[\begin{array}{cc}
1 & 0 \\
3 & -2
\end{array}\right]=\left[\begin{array}{cc}
0+1 & 1+0 \\
-2+3 & -3+(-2)
\end{array}\right]=\left[\begin{array}{cc}
1 & 1 \\
1 & -5
\end{array}\right]
$$


Matrix Subtraction:

$$
A-\mathrm{B}=\left[\begin{array}{cc}
0 & 1 \\
-2 & -3
\end{array}\right]-\left[\begin{array}{cc}
1 & 0 \\
3 & -2
\end{array}\right]=\left[\begin{array}{cc}
0-1 & 1-0 \\
-2-3 & -3-(-2)
\end{array}\right]=\left[\begin{array}{cc}
-1 & 1 \\
-5 & -1
\end{array}\right]
$$


Matrix Multiplication:

$$
A B=\left[\begin{array}{cc}
0 & 1 \\
-2 & -3
\end{array}\right]\left[\begin{array}{cc}
1 & 0 \\
3 & -2
\end{array}\right]==\left[\begin{array}{cc}
0 \cdot 1+1 \cdot 3 & 0 \cdot 0+1 \cdot(-2) \\
-2 \cdot 1-3 \cdot 3 & -2 \cdot 0-3 \cdot(-2)
\end{array}\right]=\left[\begin{array}{cc}
3 & -2 \\
-11 & 6
\end{array}\right]
$$


<IPython.core.display.Latex object>

In [17]:
import numpy as np
A = np.array([[0, 1],
                [-2, -3]])
B = np.array([[1, 0],
            [3, -2]])
print("Addition")
C = A + B
print("A+B =", C)
print(" ")
print("Subtraction")
C = A - B
print("A-B =", C)
print(" ")
print("Multiplication (elementwise)")
C = A * B
print("A*B =", C) # Not Working!, only elementwise multiplication!

print(" ")

print("Alternatives")
print("1: A.dot(B)")
#Working Alternative 1
C = A.dot(B)
print("A*B =", C)
print(" ")
print("2: np.dot")
#Working Alternative 2
C = np.dot(A,B)
print("A*B =", C)
print(" ")
print("3: np.mat * np.mat (not advised)")
#Working Alternative 3
C = np.mat(A) * np.mat(B)
print("A*B =", C)
print(" ")
print("4: np.matmul")
#Working Alternative 4
C = np.matmul(A,B)
print("A*B =", C)
print(" ")

Addition
A+B = [[ 1  1]
 [ 1 -5]]
 
Subtraction
A-B = [[-1  1]
 [-5 -1]]
 
Multiplication (elementwise)
A*B = [[ 0  0]
 [-6  6]]
 
Alternatives
1
A*B = [[  3  -2]
 [-11   6]]
 
2
A*B = [[  3  -2]
 [-11   6]]
 
3
A*B = [[  3  -2]
 [-11   6]]
 
4
A*B = [[  3  -2]
 [-11   6]]
 


In [19]:
%%latex
Remember that in matrix multiplication the matrices do not need to be quadratic, but the inner dimensions need to be the same. The size of the resulting matrix will be the outer dimensions.

$$
\begin{aligned}
& {[A] \times[B]=[C]} \\
& (n \times m) \quad(m \times p) \quad(n \times p)
\end{aligned}
$$

Inner dimensions need to be the same; the resulting matrix will be the outer dimensions.

<IPython.core.display.Latex object>

In [31]:
%%latex


dim(A) = (3x3)
$$
A=\left[\begin{array}{lll}
1 & 5 & 3 \\
4 & 6 & 6 \\
3 & 8 & 9
\end{array}\right] \quad
$$

dim(B)=(3x4)
$$
B=\left[\begin{array}{llll}
1 & 5 & 3 & 4 \\
4 & 5 & 7 & 8 \\
7 & 8 & 9 & 3
\end{array}\right] \\
$$

dim(C)=(3x1)
$$
C=\left[\begin{array}{l}
1 \\
4 \\
3
\end{array}\right]
$$

dim(D)=(1x3)
$$
D = \left[\begin{array}{l}
1 \: 5 \: 3
\end{array} \right]
$$




<IPython.core.display.Latex object>

In [32]:
%%latex


\begin{array}{l}
A \times C=(3 \times 3) \times(3 \times 1)=(3 \times 1) \\
C \times A=(3 \times 1) \times(3 \times 3)=\text { Not Legal } \\
C \times D=(3 \times 1) \times(1 \times 3)=(3 \times 3) \\
D \times C=(1 \times 3) \times(3 \times 1)=(1 \times 1)
\end{array} \quad 

$$


<IPython.core.display.Latex object>

In [38]:

import numpy as np
A = np.array([[1, 5, 3],
        [4, 6, 6],
        [3, 8, 9]])
print(" ")
print("A:",A)
B = np.array([[1, 5, 3, 4],
        [4, 5, 7, 8],
        [7, 8, 9, 3]])
print(" ")
print("B:",B)
print(" ")
C = np.array([[1],
        [4],
        [3]])
print(" ")
print("C:",C)
print(" ")
D = np.array([[1, 5, 3]])
print(" ")
print("D:",D)
print(" ")
print(" ")
print("M=np.matmul(A,B)")
M = np.matmul(A,B)
print("M=", M)
#M = np.matmul(B,A) # Not Working!
print(" ")
print("M=np.matmul(A,C)")
M = np.matmul(A,C)
print("M=", M)
#M = np.matmul(C,A) # Not Working!
print(" ")
print("M=np.matmul(C,D)")
M = np.matmul(C,D)
print("M=", M)

print(" ")
print("M=np.matmul(D,C)")
M = np.matmul(D,C)
print("M=", M)


 
A: [[1 5 3]
 [4 6 6]
 [3 8 9]]
 
B: [[1 5 3 4]
 [4 5 7 8]
 [7 8 9 3]]
 
 
C: [[1]
 [4]
 [3]]
 
 
D: [[1 5 3]]
 
 
M=np.matmul(A,B)
M= [[ 42  54  65  53]
 [ 70  98 108  82]
 [ 98 127 146 103]]
 
M=np.matmul(A,C)
M= [[30]
 [46]
 [62]]
 
M=np.matmul(C,D)
M= [[ 1  5  3]
 [ 4 20 12]
 [ 3 15  9]]
 
M=np.matmul(D,C)
M= [[30]]


In [41]:
%%latex
Transpose of a Matrix
$$
\begin{aligned}
& A=\left[\begin{array}{cccc}
1 & 3 & 7 & 2 \\
5 & 8 & -9 & 0 \\
6 & -7 & 11 & 12
\end{array}\right] \quad \Rightarrow \quad A^T=\left[\begin{array}{ccc}
1 & 5 & 6 \\
3 & 8 & -7 \\
7 & -9 & 11 \\
2 & 0 & 12
\end{array}\right] \\
& B=\left[\begin{array}{ll}
1 & 5 \\
4 & 5 \\
3 & 2 \\
7 & 8
\end{array}\right] \quad \Rightarrow \quad B^T=\left[\begin{array}{llll}
1 & 4 & 3 & 7 \\
5 & 5 & 2 & 8
\end{array}\right]
\end{aligned}
$$


<IPython.core.display.Latex object>

In [42]:
import numpy as np
A = np.array([[1, 3, 7, 2],
        [5, 8, -9, 0],
        [6, -7, 11, 12]])
print("A="); print(A)
Atr = np.transpose(A)
print("Transpose of A="); print(Atr)
B = np.array([[1, 5],
        [4,5],
        [3, 2],
        [7, 8]])
print("B="); print(B)
Btr = np.transpose(B)
print("Transpose of B="); print(Btr)


A=
[[ 1  3  7  2]
 [ 5  8 -9  0]
 [ 6 -7 11 12]]
Transpose of A=
[[ 1  5  6]
 [ 3  8 -7]
 [ 7 -9 11]
 [ 2  0 12]]
B=
[[1 5]
 [4 5]
 [3 2]
 [7 8]]
Transpose of B=
[[1 4 3 7]
 [5 5 2 8]]


In [45]:
%w%latex
Given a matrix $A$ the Determinant is given by:

$$
\operatorname{det}(A)=|A|
$$


For a $2 x 2$ matrix we have:

$$
A=\left[\begin{array}{ll}
a_{11} & a_{12} \\
a_{21} & a_{22}
\end{array}\right] \Rightarrow \operatorname{det}(A)=|A|=a_{11} a_{22}-a_{21} a_{12}
$$


Example:

$$
A=\left[\begin{array}{ll}
1 & 2 \\
3 & 4
\end{array}\right] \Rightarrow \operatorname{det}(A)=|A|=1 \cdot 4-3 \cdot 2=4-6=\underline{\underline{-2}}
$$


<IPython.core.display.Latex object>

In [49]:
%%latex
$\begin{aligned} & A=\left[\begin{array}{ll}1 & 2 \\ 3 & 4\end{array}\right] \\ & \quad \operatorname{det}(A)=-2\end{aligned}$

<IPython.core.display.Latex object>

In [50]:
%%latex
$\begin{array}{r}B=\left[\begin{array}{ccc}-1 & 3 & 0 \\ 2 & 1 & -5 \\ 1 & 4 & -2\end{array}\right] \\ \\ \operatorname{det}(B)=-21\end{array}$

<IPython.core.display.Latex object>

In [52]:
import numpy as np
import numpy.linalg as la
A = np.array([[1, 2],
        [3, 4]])
print("A:",A)
print(" ")
print("det(A)")
Adet = la.det(A)
print(Adet)
B = np.array([[-1, 3, 0],
        [2, 1, -5],
        [1, 4, -2]])
print("B:",B)
print(" ")
print("det(B)")
Bdet = la.det(B)

print(Bdet)


A: [[1 2]
 [3 4]]
 
det(A)
-2.0000000000000004
B: [[-1  3  0]
 [ 2  1 -5]
 [ 1  4 -2]]
 
det(B)
-21.00000000000001


In [53]:
%%latex
Inverse Matrices

<IPython.core.display.Latex object>

In [54]:
%%latex 
$\begin{aligned} & A=\left[\begin{array}{ll}1 & 2 \\ 3 & 4\end{array}\right] \\ & A^{-1}=\left[\begin{array}{cc}-2 & 1 \\ 1.5 & -0.5\end{array}\right]\end{aligned}$

<IPython.core.display.Latex object>

In [55]:
%%latex
$\begin{gathered}B=\left[\begin{array}{ccc}-1 & 3 & 0 \\ 2 & 1 & -5 \\ 1 & 4 & -2\end{array}\right] \\ B^{-1}=?\end{gathered}$

<IPython.core.display.Latex object>

In [59]:
import numpy as np
import numpy.linalg as la
A = np.array([[1, 2],
        [3, 4]])
print("A:", A)

print(" ")
Ainv = la.inv(A)
print("Ainv: ",Ainv)
print(" ")
B = np.array([[-1, 3, 0],
        [2, 1, -5],
        [1, 4, -2]])
print("B:",B)
Binv = la.inv(B)
print(" ")
print("Binv")
print(Binv)


A: [[1 2]
 [3 4]]
 
Ainv:  [[-2.   1. ]
 [ 1.5 -0.5]]
 
B: [[-1  3  0]
 [ 2  1 -5]
 [ 1  4 -2]]
 
Binv
[[-0.85714286 -0.28571429  0.71428571]
 [ 0.04761905 -0.0952381   0.23809524]
 [-0.33333333 -0.33333333  0.33333333]]


In [60]:
%%latex
The Eigenvalues for a given matrix $A$ is: $\operatorname{det}(\lambda I-A)=0$

<IPython.core.display.Latex object>

In [62]:
%%latex
Example: $\quad A=\left[\begin{array}{cc}0 & 1 \\ -2 & -3\end{array}\right]$

<IPython.core.display.Latex object>

In [64]:
%%latex
$\operatorname{eig}(A)=\left[\begin{array}{l}-1 \\ -2\end{array}\right]$

<IPython.core.display.Latex object>

In [66]:
%%latex
$\lambda_1=-1, \lambda_2=-2$

<IPython.core.display.Latex object>

In [74]:
import numpy as np
import numpy.linalg as la

A = np.array([[0,1],[-2,-3]])
print("A")
Aeig,v=la.eig(A)
print("Aeig,v=la.eig(A)")
print("Note how this function gets you two outputs")
print("")
print("Eigenvalues of A")
print(Aeig)

A
Aeig,v=la.eig(A)
Note how this function gets you two outputs

Eigenvalues of A
[-1. -2.]
